### ISSUE TITLE
PLCC result in KonViD-1k database 

### ISSUE THREAD

**Issue by hello02world** [junyongyou/lsct_phiqnet#1]
Why I use the pretrain PHIQNet and hyper-parameters of Conv1D{filters=[32,64]} and LSCT{L=2, D=32, heads=4, dff=64} ,but do not get average evaluation result PLCC of 0.86 in KonViD-1k database as the paper said.

**Comment by junyongyou** [comment]
Hi, if you train the model on your own, the results can be affected by many different things. I also found in some splits, the PLCC values are around ~0.80.
